const chapter01 = [
  {
    "chapterNumber": 1,
    "verseNumber": 1,
    "sanskrit": "धर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः ।\nमामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय ॥",
    "transliteration": "dharmakṣetre kurukṣetre samavetā yuyutsavaḥ / māmakāḥ pāṇḍavāścaiva kimakurvata sañjaya",
    "hindiMeaning": "हे संजय, धर्मक्षेत्र कुरुक्षेत्र में युद्ध की इच्छा से एकत्र हुए मेरे पुत्रों और पांडु के पुत्रों ने क्या किया?",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "dharma"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 2,
    "sanskrit": "दृष्ट्वा तु पाण्डवानीकं व्यूढं दुर्योधनस्तदा ।\nआचार्यमुपसङ्गम्य राजा वचनमब्रवीत् ॥",
    "transliteration": "dṛṣṭvā tu pāṇḍavānīkaṁ vyūḍhaṁ duryodhanastadā / ācāryamupasaṅgamya rājā vacanamabravīt",
    "hindiMeaning": "पांडवों की सेना को व्यूह में खड़ी देखकर राजा दुर्योधन अपने आचार्य के पास गया और उसने ये वचन कहे।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 3,
    "sanskrit": "पश्यैतां पाण्डुपुत्राणामाचार्य महतीं चमूम् ।\nव्यूढां द्रुपदपुत्रेण तव शिष्येण धीमता ॥",
    "transliteration": "paśyaitāṁ pāṇḍuputrāṇāmācārya mahatīṁ camūm / vyūḍhāṁ drupadaputreṇa tava śiṣyeṇa dhīmatā",
    "hindiMeaning": "हे आचार्य, पांडु के पुत्रों की इस विशाल सेना को देखिए, जिसे आपके ही बुद्धिमान शिष्य द्रुपद-पुत्र ने व्यूह में खड़ा किया है।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 4,
    "sanskrit": "अत्र शूरा महेष्वासा भीमार्जुनसमा युधि ।\nयुयुधानो विराटश्च द्रुपदश्च महारथः ॥",
    "transliteration": "atra śūrā maheṣvāsā bhīmārjunasamā yudhi / yuyudhāno virāṭaśca drupadaśca mahārathaḥ",
    "hindiMeaning": "यहाँ भीम और अर्जुन के समान युद्ध में शूरवीर और महान धनुर्धर हैं — युयुधान, विराट और महारथी द्रुपद।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 5,
    "sanskrit": "धृष्टकेतुश्चेकितानः काशिराजश्च वीर्यवान् ।\nपुरुजित्कुन्तिभोजश्च शैब्यश्च नरपुङ्गवः ॥",
    "transliteration": "dhṛṣṭaketuścekitānaḥ kāśirājaśca vīryavān / purujitkuntibhojaśca śaibyaśca narapuṅgavaḥ",
    "hindiMeaning": "धृष्टकेतु, चेकितान और पराक्रमी काशिराज; पुरुजित्, कुंतिभोज और नरश्रेष्ठ शैब्य भी यहाँ हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 6,
    "sanskrit": "युधामन्युश्च विक्रान्त उत्तमौजाश्च वीर्यवान् ।\nसौभद्रो द्रौपदेयाश्च सर्व एव महारथाः ॥",
    "transliteration": "yudhāmanyuśca vikrānta uttamaujāśca vīryavān / saubhadro draupadeyāśca sarva eva mahārathāḥ",
    "hindiMeaning": "पराक्रमी युधामन्यु और वीर उत्तमौजा, सुभद्रा का पुत्र और द्रौपदी के पुत्र — ये सब भी महारथी हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 7,
    "sanskrit": "अस्माकं तु विशिष्टा ये तान्निबोध द्विजोत्तम ।\nनायका मम सैन्यस्य संज्ञार्थं तान्ब्रवीमि ते ॥",
    "transliteration": "asmākaṁ tu viśiṣṭā ye tānnibodha dvijottama / nāyakā mama sainyasya saṁjñārthaṁ tānbravīmi te",
    "hindiMeaning": "हे द्विजश्रेष्ठ, हमारी ओर के जो विशिष्ट योद्धा हैं, मेरी सेना के नायक हैं, उन्हें भी जान लीजिए। पहचान के लिए मैं आपको उनके नाम बताता हूँ।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 8,
    "sanskrit": "भवान्भीष्मश्च कर्णश्च कृपश्च समितिञ्जयः ।\nअश्वत्थामा विकर्णश्च सौमदत्तिस्तथैव च ॥",
    "transliteration": "bhavānbhīṣmaśca karṇaśca kṛpaśca samitiñjayaḥ / aśvatthāmā vikarṇaśca saumadattistathaiva ca",
    "hindiMeaning": "आप स्वयं, भीष्म, कर्ण और संग्रामविजयी कृपाचार्य; अश्वत्थामा, विकर्ण और सोमदत्त का पुत्र भी हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 9,
    "sanskrit": "अन्ये च बहवः शूरा मदर्थे त्यक्तजीविताः ।\nनानाशस्त्रप्रहरणाः सर्वे युद्धविशारदाः ॥",
    "transliteration": "anye ca bahavaḥ śūrā madarthe tyaktajīvitāḥ / nānāśastrapraharaṇāḥ sarve yuddhaviśāradāḥ",
    "hindiMeaning": "और भी बहुत से शूरवीर मेरे लिए अपने प्राण त्यागने को तैयार हैं। वे अनेक प्रकार के शस्त्र लिए हुए हैं और सभी युद्ध में निपुण हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 10,
    "sanskrit": "अपर्याप्तं तदस्माकं बलं भीष्माभिरक्षितम् ।\nपर्याप्तं त्विदमेतेषां बलं भीमाभिरक्षितम् ॥",
    "transliteration": "aparyāptaṁ tadasmākaṁ balaṁ bhīṣmābhirakṣitam / paryāptaṁ tvidameteṣāṁ balaṁ bhīmābhirakṣitam",
    "hindiMeaning": "भीष्म द्वारा रक्षित हमारा यह बल अपरिमित है, जबकि भीम द्वारा रक्षित इनका बल सीमित है।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 11,
    "sanskrit": "अयनेषु च सर्वेषु यथाभागमवस्थिताः ।\nभीष्ममेवाभिरक्षन्तु भवन्तः सर्व एव हि ॥",
    "transliteration": "ayaneṣu ca sarveṣu yathābhāgamavasthitāḥ / bhīṣmamevābhirakṣantu bhavantaḥ sarva eva hi",
    "hindiMeaning": "इसलिए सब मोर्चों पर अपने-अपने नियत स्थान पर स्थित रहकर आप सब लोग निश्चय ही भीष्म की रक्षा करें।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 12,
    "sanskrit": "तस्य सञ्जनयन्हर्षं कुरुवृद्धः पितामहः ।\nसिंहनादं विनद्योच्चैः शङ्खं दध्मौ प्रतापवान् ॥",
    "transliteration": "tasya sañjanayanharṣaṁ kuruvṛddhaḥ pitāmahaḥ / siṁhanādaṁ vinadyoccaiḥ śaṅkhaṁ dadhmau pratāpavān",
    "hindiMeaning": "तब कुरुवृद्ध प्रतापी पितामह भीष्म ने दुर्योधन के हृदय में हर्ष भरते हुए सिंह के समान गरजकर अपना शंख बजाया।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 13,
    "sanskrit": "ततः शङ्खाश्च भेर्यश्च पणवानकगोमुखाः ।\nसहसैवाभ्यहन्यन्त स शब्दस्तुमुलोऽभवत् ॥",
    "transliteration": "tataḥ śaṅkhāśca bheryaśca paṇavānakagomukhāḥ / sahasaivābhyahanyanta sa śabdastumulo’bhavat",
    "hindiMeaning": "फिर शंख, नगाड़े, ढोल, मृदंग और नरसिंघे एक साथ बज उठे, और उनका वह शब्द बड़ा भयंकर हुआ।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 14,
    "sanskrit": "ततः श्वेतैर्हयैर्युक्ते महति स्यन्दने स्थितौ ।\nमाधवः पाण्डवश्चैव दिव्यौ शङ्खौ प्रदध्मतुः ॥",
    "transliteration": "tataḥ śvetairhayairyukte mahati syandane sthitau / mādhavaḥ pāṇḍavaścaiva divyau śaṅkhau pradadhmatuḥ",
    "hindiMeaning": "फिर श्वेत घोड़ों से जुते हुए विशाल रथ में बैठे माधव और पांडुपुत्र अर्जुन ने अपने दिव्य शंख बजाए।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 15,
    "sanskrit": "पाञ्चजन्यं हृषीकेशो देवदत्तं धनञ्जयः ।\nपौण्ड्रं दध्मौ महाशङ्खं भीमकर्मा वृकोदरः ॥",
    "transliteration": "pāñcajanyaṁ hṛṣīkeśo devadattaṁ dhanañjayaḥ / pauṇḍraṁ dadhmau mahāśaṅkhaṁ bhīmakarmā vṛkodaraḥ",
    "hindiMeaning": "हृषीकेश ने पांचजन्य और धनंजय ने देवदत्त बजाया, तथा भयंकर कर्म करने वाले वृकोदर भीम ने पौंड्र नामक महाशंख बजाया।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "karma"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 16,
    "sanskrit": "अनन्तविजयं राजा कुन्तीपुत्रो युधिष्ठिरः ।\nनकुलः सहदेवश्च सुघोषमणिपुष्पकौ ॥",
    "transliteration": "anantavijayaṁ rājā kuntīputro yudhiṣṭhiraḥ / nakulaḥ sahadevaśca sughoṣamaṇipuṣpakau",
    "hindiMeaning": "कुंतीपुत्र राजा युधिष्ठिर ने अनंतविजय तथा नकुल और सहदेव ने सुघोष और मणिपुष्पक नामक शंख बजाए।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 17,
    "sanskrit": "काश्यश्च परमेष्वासः शिखण्डी च महारथः ।\nधृष्टद्युम्नो विराटश्च सात्यकिश्चापराजितः ॥",
    "transliteration": "kāśyaśca parameṣvāsaḥ śikhaṇḍī ca mahārathaḥ / dhṛṣṭadyumno virāṭaśca sātyakiścāparājitaḥ",
    "hindiMeaning": "परम धनुर्धर काशिराज, महारथी शिखंडी, धृष्टद्युम्न, विराट और अजेय सात्यकि —",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 18,
    "sanskrit": "द्रुपदो द्रौपदेयाश्च सर्वशः पृथिवीपते ।\nसौभद्रश्च महाबाहुः शङ्खान्दध्मुः पृथक्पृथक् ॥",
    "transliteration": "drupado draupadeyāśca sarvaśaḥ pṛthivīpate / saubhadraśca mahābāhuḥ śaṅkhāndadhmuḥ pṛthakpṛthak",
    "hindiMeaning": "द्रुपद, द्रौपदी के पुत्र और महाबाहु सुभद्रापुत्र — हे राजन्, इन सबने अलग-अलग अपने-अपने शंख बजाए।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 19,
    "sanskrit": "स घोषो धार्तराष्ट्राणां हृदयानि व्यदारयत् ।\nनभश्च पृथिवीं चैव तुमुलोऽभ्यनुनादयन् ॥",
    "transliteration": "sa ghoṣo dhārtarāṣṭrāṇāṁ hṛdayāni vyadārayat / nabhaśca pṛthivīṁ caiva tumulo’bhyanunādayan",
    "hindiMeaning": "उस घोष ने धृतराष्ट्र के पुत्रों के हृदय चीर दिए, और उस तुमुल नाद से आकाश और पृथ्वी दोनों गूँज उठे।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 20,
    "sanskrit": "अथ व्यवस्थितान्दृष्ट्वा धार्तराष्ट्रान्कपिध्वजः ।\nप्रवृत्ते शस्त्रसम्पाते धनुरुद्यम्य पाण्डवः ।\nहृषीकेशं तदा वाक्यमिदमाह महीपते ॥",
    "transliteration": "atha vyavasthitāndṛṣṭvā dhārtarāṣṭrānkapidhvajaḥ / pravṛtte śastrasampāte dhanurudyamya pāṇḍavaḥ / hṛṣīkeśaṁ tadā vākyamidamāha mahīpate",
    "hindiMeaning": "हे राजन्, तब धृतराष्ट्र के पुत्रों को मोर्चे पर खड़ा देखकर और शस्त्र चलने को तैयार जानकर, कपिध्वज पांडुपुत्र अर्जुन ने धनुष उठाकर हृषीकेश से ये वचन कहे।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 21,
    "sanskrit": "सेनयोरुभयोर्मध्ये रथं स्थापय मेऽच्युत ॥",
    "transliteration": "senayorubhayormadhye rathaṁ sthāpaya me’cyuta",
    "hindiMeaning": "हे अच्युत, मेरे रथ को दोनों सेनाओं के बीच में खड़ा कीजिए।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 22,
    "sanskrit": "यावदेतान्निरीक्षेऽहं योद्धुकामानवस्थितान् ।\nकैर्मया सह योद्धव्यमस्मिन् रणसमुद्यमे ॥",
    "transliteration": "yāvadetānnirīkṣe’haṁ yoddhukāmānavasthitān / kairmayā saha yoddhavyamasmin raṇasamudyame",
    "hindiMeaning": "जिससे मैं युद्ध की इच्छा से खड़े हुए इन योद्धाओं को देख सकूँ और जान सकूँ कि इस रण-उद्यम में मुझे किनके साथ लड़ना है।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "kama"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 23,
    "sanskrit": "योत्स्यमानानवेक्षेऽहं य एतेऽत्र समागताः ।\nधार्तराष्ट्रस्य दुर्बुद्धेर्युद्धे प्रियचिकीर्षवः ॥",
    "transliteration": "yotsyamānānavekṣe’haṁ ya ete’tra samāgatāḥ / dhārtarāṣṭrasya durbuddheryuddhe priyacikīrṣavaḥ",
    "hindiMeaning": "मैं उन्हें देखना चाहता हूँ जो यहाँ युद्ध के लिए एकत्र हुए हैं और दुर्बुद्धि धृतराष्ट्रपुत्र का युद्ध में प्रिय करना चाहते हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 24,
    "sanskrit": "एवमुक्तो हृषीकेशो गुडाकेशेन भारत ।\nसेनयोरुभयोर्मध्ये स्थापयित्वा रथोत्तमम् ॥",
    "transliteration": "evamukto hṛṣīkeśo guḍākeśena bhārata / senayorubhayormadhye sthāpayitvā rathottamam",
    "hindiMeaning": "हे भारत, गुडाकेश अर्जुन के ऐसा कहने पर हृषीकेश ने दोनों सेनाओं के बीच में उस उत्तम रथ को खड़ा कर दिया।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 25,
    "sanskrit": "भीष्मद्रोणप्रमुखतः सर्वेषां च महीक्षिताम् ।\nउवाच पार्थ पश्यैतान्समवेतान्कुरूनिति ॥",
    "transliteration": "bhīṣmadroṇapramukhataḥ sarveṣāṁ ca mahīkṣitām / uvāca pārtha paśyaitānsamavetānkurūniti",
    "hindiMeaning": "भीष्म और द्रोण के सामने तथा सब राजाओं के सामने उन्होंने कहा — हे पार्थ, यहाँ एकत्र हुए इन कौरवों को देखो।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 26,
    "sanskrit": "तत्रापश्यत्स्थितान्पार्थः पितॄनथ पितामहान् ।\nआचार्यान्मातुलान्भ्रातॄन्पुत्रान्पौत्रान्सखींस्तथा ॥",
    "transliteration": "tatrāpaśyatsthitānpārthaḥ pitṝnatha pitāmahān / ācāryānmātulānbhrātṝnputrānpautrānsakhīṁstathā",
    "hindiMeaning": "वहाँ पार्थ ने खड़े हुए पिताओं और पितामहों को, आचार्यों, मामाओं, भाइयों, पुत्रों, पौत्रों और मित्रों को भी देखा।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 27,
    "sanskrit": "श्वशुरान्सुहृदश्चैव सेनयोरुभयोरपि ।\nतान्समीक्ष्य स कौन्तेयः सर्वान्बन्धूनवस्थितान् ।\nकृपया परयाविष्टो विषीदन्निदमब्रवीत् ॥",
    "transliteration": "śvaśurānsuhṛdaścaiva senayorubhayorapi / tānsamīkṣya sa kaunteyaḥ sarvānbandhūnavasthitān / kṛpayā parayāviṣṭo viṣīdannidamabravīt",
    "hindiMeaning": "दोनों सेनाओं में ससुरों और सुहृदों को भी देखकर, वहाँ खड़े इन सब बंधुओं को देखकर कुंतीपुत्र अर्जुन अत्यंत करुणा से भर गया और शोक में यह बोला।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 28,
    "sanskrit": "दृष्ट्वेमं स्वजनं कृष्ण युयुत्सुं समुपस्थितम् ॥",
    "transliteration": "dṛṣṭvemaṁ svajanaṁ kṛṣṇa yuyutsuṁ samupasthitam",
    "hindiMeaning": "हे कृष्ण, युद्ध की इच्छा से यहाँ उपस्थित अपने ही स्वजनों को मैं देख रहा हूँ।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 29,
    "sanskrit": "सीदन्ति मम गात्राणि मुखं च परिशुष्यति ।\nवेपथुश्च शरीरे मे रोमहर्षश्च जायते ॥",
    "transliteration": "sīdanti mama gātrāṇi mukhaṁ ca pariśuṣyati / vepathuśca śarīre me romaharṣaśca jāyate",
    "hindiMeaning": "मेरे अंग शिथिल हो रहे हैं और मुख सूखा जा रहा है। मेरा शरीर काँप रहा है और रोंगटे खड़े हो रहे हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 30,
    "sanskrit": "गाण्डीवं स्रंसते हस्तात्त्वक्चैव परिदह्यते ।\nन च शक्नोम्यवस्थातुं भ्रमतीव च मे मनः ॥",
    "transliteration": "gāṇḍīvaṁ sraṁsate hastāttvakcaiva paridahyate / na ca śaknomyavasthātuṁ bhramatīva ca me manaḥ",
    "hindiMeaning": "गांडीव हाथ से गिर रहा है और त्वचा जल रही है। मैं खड़ा भी नहीं रह पा रहा, और मेरा मन भटक-सा रहा है।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 31,
    "sanskrit": "निमित्तानि च पश्यामि विपरीतानि केशव ।\nन च श्रेयोऽनुपश्यामि हत्वा स्वजनमाहवे ॥",
    "transliteration": "nimittāni ca paśyāmi viparītāni keśava / na ca śreyo’nupaśyāmi hatvā svajanamāhave",
    "hindiMeaning": "हे केशव, मुझे विपरीत लक्षण दिखाई दे रहे हैं। युद्ध में अपने ही स्वजनों को मारकर मुझे कोई कल्याण नहीं दिखता।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 32,
    "sanskrit": "न काङ्क्षे विजयं कृष्ण न च राज्यं सुखानि च ।\nकिं नो राज्येन गोविन्द किं भोगैर्जीवितेन वा ॥",
    "transliteration": "na kāṅkṣe vijayaṁ kṛṣṇa na ca rājyaṁ sukhāni ca / kiṁ no rājyena govinda kiṁ bhogairjīvitena vā",
    "hindiMeaning": "हे कृष्ण, मुझे न विजय चाहिए, न राज्य और न सुख। हे गोविंद, हमें राज्य से क्या, भोगों से क्या, और जीने से भी क्या?",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "sukha"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 33,
    "sanskrit": "येषामर्थे काङ्क्षितं नो राज्यं भोगाः सुखानि च ।\nत इमेऽवस्थिता युद्धे प्राणांस्त्यक्त्वा धनानि च ॥",
    "transliteration": "yeṣāmarthe kāṅkṣitaṁ no rājyaṁ bhogāḥ sukhāni ca / ta ime’vasthitā yuddhe prāṇāṁstyaktvā dhanāni ca",
    "hindiMeaning": "जिनके लिए हमें राज्य, भोग और सुख की इच्छा थी, वे ही प्राण और धन का मोह छोड़कर इस युद्ध में खड़े हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "sukha"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 34,
    "sanskrit": "आचार्याः पितरः पुत्रास्तथैव च पितामहाः ।\nमातुलाः श्वशुराः पौत्राः श्यालाः सम्बन्धिनस्तथा ॥",
    "transliteration": "ācāryāḥ pitaraḥ putrāstathaiva ca pitāmahāḥ / mātulāḥ śvaśurāḥ pautrāḥ śyālāḥ sambandhinastathā",
    "hindiMeaning": "आचार्य, पिता, पुत्र और पितामह; मामा, ससुर, पौत्र, साले और दूसरे संबंधी भी यहीं हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 35,
    "sanskrit": "एतान्न हन्तुमिच्छामि घ्नतोऽपि मधुसूदन ।\nअपि त्रैलोक्यराज्यस्य हेतोः किं नु महीकृते ॥",
    "transliteration": "etānna hantumicchāmi ghnato’pi madhusūdana / api trailokyarājyasya hetoḥ kiṁ nu mahīkṛte",
    "hindiMeaning": "हे मधुसूदन, ये मुझे मार भी डालें तो भी मैं इन्हें मारना नहीं चाहता — तीनों लोकों के राज्य के लिए भी नहीं, फिर पृथ्वी के लिए तो क्या?",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 36,
    "sanskrit": "निहत्य धार्तराष्ट्रान्नः का प्रीतिः स्याज्जनार्दन ।\nपापमेवाश्रयेदस्मान्हत्वैतानाततायिनः ॥",
    "transliteration": "nihatya dhārtarāṣṭrānnaḥ kā prītiḥ syājjanārdana / pāpamevāśrayedasmānhatvaitānātatāyinaḥ",
    "hindiMeaning": "हे जनार्दन, धृतराष्ट्र के पुत्रों को मारकर हमें क्या प्रसन्नता मिलेगी? इन आततायियों को मारकर हमें पाप ही लगेगा।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 37,
    "sanskrit": "तस्मान्नार्हा वयं हन्तुं धार्तराष्ट्रान्स्वबान्धवान् ।\nस्वजनं हि कथं हत्वा सुखिनः स्याम माधव ॥",
    "transliteration": "tasmānnārhā vayaṁ hantuṁ dhārtarāṣṭrānsvabāndhavān / svajanaṁ hi kathaṁ hatvā sukhinaḥ syāma mādhava",
    "hindiMeaning": "इसलिए हे माधव, अपने ही बांधव धृतराष्ट्रपुत्रों को मारना हमारे लिए उचित नहीं। अपने स्वजनों को मारकर हम सुखी कैसे होंगे?",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "sukha"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 38,
    "sanskrit": "यद्यप्येते न पश्यन्ति लोभोपहतचेतसः ।\nकुलक्षयकृतं दोषं मित्रद्रोहे च पातकम् ॥",
    "transliteration": "yadyapyete na paśyanti lobhopahatacetasaḥ / kulakṣayakṛtaṁ doṣaṁ mitradrohe ca pātakam",
    "hindiMeaning": "यद्यपि लोभ से जिनकी बुद्धि हर ली गई है, वे कुल के नाश में दोष और मित्र से द्रोह में पाप नहीं देखते —",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "lobha",
      "manas"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 39,
    "sanskrit": "कथं न ज्ञेयमस्माभिः पापादस्मान्निवर्तितुम् ।\nकुलक्षयकृतं दोषं प्रपश्यद्भिर्जनार्दन ॥",
    "transliteration": "kathaṁ na jñeyamasmābhiḥ pāpādasmānnivartitum / kulakṣayakṛtaṁ doṣaṁ prapaśyadbhirjanārdana",
    "hindiMeaning": "पर हे जनार्दन, कुल के नाश के दोष को स्पष्ट देखने वाले हम इस पाप से क्यों न हटें?",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "jnana"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 40,
    "sanskrit": "कुलक्षये प्रणश्यन्ति कुलधर्माः सनातनाः ।\nधर्मे नष्टे कुलं कृत्स्नमधर्मोऽभिभवत्युत ॥",
    "transliteration": "kulakṣaye praṇaśyanti kuladharmāḥ sanātanāḥ / dharme naṣṭe kulaṁ kṛtsnamadharmo’bhibhavatyuta",
    "hindiMeaning": "कुल के नाश से कुल के सनातन धर्म नष्ट हो जाते हैं, और धर्म के नष्ट होने पर सारे कुल को अधर्म दबा लेता है।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "dharma"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 41,
    "sanskrit": "अधर्माभिभवात्कृष्ण प्रदुष्यन्ति कुलस्त्रियः ।\nस्त्रीषु दुष्टासु वार्ष्णेय जायते वर्णसङ्करः ॥",
    "transliteration": "adharmābhibhavātkṛṣṇa praduṣyanti kulastriyaḥ / strīṣu duṣṭāsu vārṣṇeya jāyate varṇasaṅkaraḥ",
    "hindiMeaning": "हे कृष्ण, अधर्म के बढ़ने पर कुल की स्त्रियाँ दूषित हो जाती हैं; और हे वार्ष्णेय, स्त्रियों के दूषित होने पर वर्णसंकर उत्पन्न होता है।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "dharma"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 42,
    "sanskrit": "सङ्करो नरकायैव कुलघ्नानां कुलस्य च ।\nपतन्ति पितरो ह्येषां लुप्तपिण्डोदकक्रियाः ॥",
    "transliteration": "saṅkaro narakāyaiva kulaghnānāṁ kulasya ca / patanti pitaro hyeṣāṁ luptapiṇḍodakakriyāḥ",
    "hindiMeaning": "वह संकर कुल के नाश करने वालों को और कुल को नरक में ही ले जाता है। पिंड और जल की क्रिया लुप्त हो जाने से उनके पितर गिर जाते हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 43,
    "sanskrit": "दोषैरेतैः कुलघ्नानां वर्णसङ्करकारकैः ।\nउत्साद्यन्ते जातिधर्माः कुलधर्माश्च शाश्वताः ॥",
    "transliteration": "doṣairetaiḥ kulaghnānāṁ varṇasaṅkarakārakaiḥ / utsādyante jātidharmāḥ kuladharmāśca śāśvatāḥ",
    "hindiMeaning": "वर्णसंकर को जन्म देने वाले कुलघातियों के इन दोषों से जाति के और कुल के शाश्वत धर्म नष्ट हो जाते हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "dharma"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 44,
    "sanskrit": "उत्सन्नकुलधर्माणां मनुष्याणां जनार्दन ।\nनरके नियतं वासो भवतीत्यनुशुश्रुम ॥",
    "transliteration": "utsannakuladharmāṇāṁ manuṣyāṇāṁ janārdana / narake niyataṁ vāso bhavatītyanuśuśruma",
    "hindiMeaning": "हे जनार्दन, हमने सुना है कि जिनके कुलधर्म नष्ट हो जाते हैं, उन मनुष्यों का नरक में वास निश्चित होता है।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "dharma"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 45,
    "sanskrit": "अहो बत महत्पापं कर्तुं व्यवसिता वयम् ।\nयद्राज्यसुखलोभेन हन्तुं स्वजनमुद्यताः ॥",
    "transliteration": "aho bata mahatpāpaṁ kartuṁ vyavasitā vayam / yadrājyasukhalobhena hantuṁ svajanamudyatāḥ",
    "hindiMeaning": "अहो! कितने खेद की बात है कि हम राज्य और सुख के लोभ से अपने ही स्वजनों को मारने को तैयार होकर महान पाप करने पर उतर आए हैं।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "lobha",
      "sukha"
    ],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 46,
    "sanskrit": "यदि मामप्रतीकारमशस्त्रं शस्त्रपाणयः ।\nधार्तराष्ट्रा रणे हन्युस्तन्मे क्षेमतरं भवेत् ॥",
    "transliteration": "yadi māmapratīkāramaśastraṁ śastrapāṇayaḥ / dhārtarāṣṭrā raṇe hanyustanme kṣemataraṁ bhavet",
    "hindiMeaning": "यदि शस्त्रधारी धृतराष्ट्रपुत्र मुझ निहत्थे और प्रतिकार न करने वाले को रण में मार डालें, तो वह भी मेरे लिए अधिक कल्याणकारी होगा।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [],
    "isFeatured": false
  },
  {
    "chapterNumber": 1,
    "verseNumber": 47,
    "sanskrit": "एवमुक्त्वार्जुनः सङ्ख्ये रथोपस्थ उपाविशत् ।\nविसृज्य सशरं चापं शोकसंविग्नमानसः ॥",
    "transliteration": "evamuktvārjunaḥ saṅkhye rathopastha upāviśat / visṛjya saśaraṁ cāpaṁ śokasaṁvignamānasaḥ",
    "hindiMeaning": "रणभूमि में ऐसा कहकर अर्जुन बाण सहित धनुष त्यागकर रथ के पिछले भाग में बैठ गया; उसका मन शोक से व्याकुल था।",
    "englishMeaning": "",
    "imageUrl": "",
    "audioSanskritUrl": "",
    "audioMeaningUrl": "",
    "tags": [
      "shoka"
    ],
    "isFeatured": false
  }
];

export default chapter01;
